### ISSUE TITLE
Needle hangs when unpacking IPA

### ISSUE THREAD

**Issue by theHackPot** [mwrlabs/needle#94] opened 2016-12-13 13:02 UTC
## Issue
Needle hangs when decrypting IPA

### Expected behaviour
Return binary strings for targeted app

### Actual behaviour
Needle hangs @ "Unpacking the decrypted IPA"

### Steps to reproduce
1. python needle.py
2. use binary/strings
3. run
4. Select target app number

### needle error logs

```
             __   _ _______ _______ ______         _______
             | \  | |______ |______ |     \ |      |______
             |  \_| |______ |______ |_____/ |_____ |______
        
                   Needle v0.0.4 [mwr.to/needle]                  
  [MWR InfoSecurity (@MWRLabs) - Marco Lancini (@LanciniMarco)]   

[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
[needle] > use binary/strings
[needle][strings] > run
[D] Setup local output folder: /Users/name/.needle/output
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/name/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[V] Setting up SSH connection...
[+] Connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[*] Target app not selected. Launching wizard...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] Copy the plist to temp: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cp /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] Converting plist to XML: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] Extracting content from: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[D] Parsing plist content
[+] Apps found:
		
		
		38 - com.microsoft.office.skydrivepro
		
Please select a number: 38
[+] Target app: com.microsoft.office.skydrivepro
[*] Retrieving app's metadata...
[D] Copy the plist to temp: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/DD0A22AB-E68B-4DEA-B33A-021B5B70451F/SkyDrivePro.app/Info.plist /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/DD0A22AB-E68B-4DEA-B33A-021B5B70451F/SkyDrivePro.app/SkyDrivePro
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/DD0A22AB-E68B-4DEA-B33A-021B5B70451F/SkyDrivePro.app/PlugIns ]; then echo "yes"; else echo "no" ; fi
[*] Decrypting the binary...
[D] [REMOTE CMD] Remote Command: Clutch2 -d com.microsoft.office.skydrivepro 2>&1
[?] The app might be already decrypted. Trying to retrieve the IPA...
[D] [REMOTE CMD] Remote Command: ipainstaller -b com.microsoft.office.skydrivepro -o /var/root/needle/decrypted.ipa
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm -rf /var/root/needle/Payload 2> /dev/null
[D] [REMOTE CMD] Remote Command: if [ -f /var/root/needle/iTunesArtwork ]; then echo "yes"; else echo "no" ; fi
[*] Unpacking the decrypted IPA...
[D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/
```

#### Workstation Operating System
MAC OSX (EL Capitan
#### Python Version
2.7.10
#### Python Packages (`pip freeze`)
altgraph==0.10.2
argh==0.26.1
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.1
bdist-mpkg==0.5.0
blinker==1.4
bonjour-py==0.3
bzip2==0.0.1
cached-property==1.3.0
certifi==2016.2.28
cffi==1.6.0
click==6.6
colorama==0.3.7
ConfigArgParse==0.10.0
configparser==3.5.0
construct==2.5.2
cryptography==1.3.2
defusedxml==0.4.1
Django==1.10b1
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
drozer==2.3.4
enum34==1.1.6
Flask==0.10.1
Flask-Caching==1.0.1
Flask-Session==0.3.0
Flask-SQLAlchemy==2.1
frida==8.2.2
functools32==3.2.3.post2
future==0.16.0
gunicorn==19.6.0
h2==2.3.0
hpack==2.2.0
html2text==2016.4.2
html5lib==0.9999999
httplib2==0.9.2
hyperframe==3.2.0
idna==2.1
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.7.3
jsonschema==2.5.1
lxml==3.6.0
macholib==1.5.1
MarkupSafe==0.23
matplotlib==1.3.1
mitmproxy==0.17
modulegraph==0.10.4
netaddr==0.7.18
nose==1.3.7
numpy==1.8.0rc1
paramiko==2.0.2
passlib==1.6.5
pathtools==0.1.2
pbkdf2==1.3
pbr==1.10.0
Pillow==3.2.0
pisa==3.0.33
prompt-toolkit==1.0.9
protobuf==2.4.1
psutil==3.2.2
py2app==0.7.3
pyasn1==0.1.9
pycparser==2.14
Pygments==2.1.3
PyMySQL==0.7.9
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
PyPDF2==1.25.1
pyperclip==1.5.27
python-dateutil==1.5
python-memcached==1.58
pytz==2013.7
PyYAML==3.11
reportlab==3.3.0
requests==2.9.2
rsa==3.4.2
scipy==0.13.0b1
singledispatch==3.4.0.3
six==1.10.0
SQLAlchemy==1.1.4
SQLAlchemy-Utils==0.32.11
sshtunnel==0.1.2
stevedore==1.15.0
texttable==0.8.7
tornado==4.3
Twisted==10.2.0
urwid==1.3.1
vboxapi==1.0
virtualenv==15.0.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
watchdog==0.8.3
wcwidth==0.1.7
websocket-client==0.39.0
Werkzeug==0.11.9
xattr==0.6.4
xhtml2pdf==0.1a3
zope.interface==4.1.

#### Device iOS Version
9.0.2

**Comment by marco-lancini** [comment] 2016-12-13 13:28
Hi @theHackPot, can you please check if `unzip` is installed on your device?

**Comment by theHackPot** [comment] 2016-12-13 13:31
Yes, unzip is installed

**Comment by theHackPot** [comment] 2016-12-13 15:26
@marco-lancini I get the following error when setting SETUP_DEVICE True. Not sure if it is related

[needle] > set SETUP_DEVICE True
SETUP_DEVICE => True
[needle] > use binary/strings
[needle][strings] > run
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2222
[V] Setting up SSH connection...
[+] Connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[*] Configuring device...
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
bzip2: (stdin) is not a bzip2 file.
W: Failed to fetch http://cydia.xsellize.com/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

W: Failed to fetch http://cydia.angelxwind.net/?page/net.angelxwind.appsyncunified/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

W: Failed to fetch http://cydia.myrepospace.com/kingkong5147/./Packages.gz  HTTP/1.1 404 Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[V] [INSTALL] Installing COREUTILS via apt-get.
[V] [INSTALL] Installing COREUTILS via apt-get.
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
bzip2: (stdin) is not a bzip2 file.
W: Failed to fetch http://cydia.angelxwind.net/?page/net.angelxwind.appsyncunified/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

W: Failed to fetch http://cydia.xsellize.com/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

W: Failed to fetch http://cydia.myrepospace.com/kingkong5147/./Packages.gz  HTTP/1.1 404 Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...

**Comment by marco-lancini** [comment] 2017-01-18 21:32
Hi @theHackPot, regarding your first issue: so Needle hangs after it prints this line?

```
[D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/
```

Regarding your second log dump, could you please enable DEBUG mode?

**Comment by theHackPot** [comment] 2017-01-19 09:40
Hi @marco-lancini ,

yes confirmed as hanging at line [D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/

Second dump with DEBUG mode True


             __   _ _______ _______ ______         _______
             | \  | |______ |______ |     \ |      |______
             |  \_| |______ |______ |_____/ |_____ |______
        
                   Needle v0.0.4 [mwr.to/needle]                  
  [MWR InfoSecurity (@MWRLabs) - Marco Lancini (@LanciniMarco)]   

[needle] > set SETUP_DEVICE True
SETUP_DEVICE => True
[needle] > set DEBUG True
DEBUG => True
[needle] > use binary/strings
[needle][strings] > run
[D] Setup local output folder: /Users/fergalcoll/.needle/output
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2222
[D] [LOCAL CMD] Local Subprocess Command: /Users/fergalcoll/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2222
[V] Setting up SSH connection...
[+] Connected to: 127.0.0.1
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[*] Configuring device...
[D] [REMOTE CMD] Remote Command: which apt-get
[D] [REMOTE CMD] Remote Command: which dpkg
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
W: Failed to fetch http://cydia.angelxwind.net/?page/net.angelxwind.appsyncunified/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

W: Failed to fetch http://cydia.myrepospace.com/kingkong5147/./Packages.gz  HTTP/1.1 404 Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[V] [INSTALL] Installing COREUTILS via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes coreutils
[?] Error occurred during installation of tools: W: Encountered a section with no Package: header
W: You may want to run apt-get update to correct these problems
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: dpkg --get-selections | grep -v "deinstall" | cut -f1
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
W: Failed to fetch http://cydia.angelxwind.net/?page/net.angelxwind.appsyncunified/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

W: Failed to fetch http://cydia.myrepospace.com/kingkong5147/./Packages.gz  HTTP/1.1 404 Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: cat /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: which FileDP
[D] [INSTALL] Tool already available: FILEDP
[D] [INSTALL] Already installed: CYCRIPT.
[D] [REMOTE CMD] Remote Command: which keychain_dump
[D] [INSTALL] Tool already available: KEYCHAIN_DUMP
[D] Installation method not provided for UIOPEN. Skipping
[D] [INSTALL] Already installed: COREUTILS.
[D] [INSTALL] Already installed: COREUTILS.
[D] [INSTALL] Already installed: FRIDA.
[D] [INSTALL] Already installed: OPEN.
[D] Installation method not provided for FIND. Skipping
[D] Installation method not provided for OTOOL. Skipping
[D] Installation method not provided for UNZIP. Skipping
[D] [REMOTE CMD] Remote Command: which fsmon
[D] [INSTALL] Tool already available: FSMON
[D] [INSTALL] Already installed: DARWINTOOLS.
[D] [INSTALL] Already installed: ONDEVICECONSOLE.
[D] [INSTALL] Already installed: BIGBOSS.
[D] [INSTALL] Already installed: SOCAT.
[D] Installation method not provided for LIPO. Skipping
[D] [INSTALL] Already installed: PLUTIL.
[D] Installation method not provided for WHICH. Skipping
[D] Installation method not provided for APT-GET. Skipping
[D] [REMOTE CMD] Remote Command: which pbwatcher
[D] [INSTALL] Tool already available: PBWATCHER
[D] Installation method not provided for STRINGS. Skipping
[D] Installation method not provided for DPKG. Skipping
[D] [INSTALL] Already installed: IPAINSTALLER.
[D] [INSTALL] Already installed: CLASS-DUMP.
[D] [INSTALL] Already installed: CLASS-DUMP.
[D] [INSTALL] Already installed: CLASS-DUMP.
[D] [INSTALL] Already installed: GDB.
[D] [INSTALL] Already installed: CLUTCH.
[D] [INSTALL] Already installed: LDID.
[*] Target app not selected. Launching wizard...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] Copy the plist to temp: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cp /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] Converting plist to XML: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] Extracting content from: /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[D] Parsing plist content
[+] Apps found:
		[Other Apps removed]
		28 - com.microsoft.skydrive
		
Please select a number: 28
[+] Target app: com.microsoft.skydrive
[*] Retrieving app's metadata...
[D] Copy the plist to temp: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/Info.plist /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/OneDrive
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: ls  /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns/OneDrive.appex ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns/OneDriveShareExtension.appex ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns/onedrivefileprovider.appex ]; then echo "yes"; else echo "no" ; fi
[D] Copy the plist to temp: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns/OneDrive.appex/Info.plist /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
[D] Copy the plist to temp: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns/OneDriveShareExtension.appex/Info.plist /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
[D] Copy the plist to temp: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/mobile/Containers/Bundle/Application/145846CE-2F61-46AD-8956-43BBB8B3D916/OneDrive.app/PlugIns/onedrivefileprovider.appex/Info.plist /var/root/needle/Info.plist
[D] Converting plist to XML: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] Extracting content from: /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] Parsing plist content
[*] Decrypting the binary...
[D] [REMOTE CMD] Remote Command: Clutch2 -d com.microsoft.skydrive 2>&1
[?] The app might be already decrypted. Trying to retrieve the IPA...
[D] [REMOTE CMD] Remote Command: ipainstaller -b com.microsoft.skydrive -o /var/root/needle/decrypted.ipa
[V] Decrypted IPA stored at: /var/root/needle/decrypted.ipa
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/Payload ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm -rf /var/root/needle/Payload 2> /dev/null
[D] [REMOTE CMD] Remote Command: if [ -f /var/root/needle/iTunesArtwork ]; then echo "yes"; else echo "no" ; fi
[*] Unpacking the decrypted IPA...
[D] [REMOTE CMD] Remote Command: unzip /var/root/needle/decrypted.ipa -d /var/root/needle/

**Comment by marco-lancini** [comment] 2017-01-19 11:16
and you can confirm that if you run unzip directly (`unzip /var/root/needle/decrypted.ipa -d /var/root/needle/`), it works fine?

**Comment by theHackPot** [comment] 2017-01-19 11:33
Yes seems to be working
```

Sec2-iPad:~/needle root# unzip decrypted.ipa -d /var/root/needle/
Archive:  decrypted.ipa
replace /var/root/needle/Payload/OneDrive.app/AEDefaultAnnouncementView.nib? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: /var/root/needle/Payload/OneDrive.app/AEDefaultAnnouncementView.nib  
  inflating: /var/root/needle/Payload/OneDrive.app/AEDefaultPollView.nib  
  inflating: /var/root/needle/Payload/OneDrive.app/AENotificationView.nib  
  inflating: /var/root/needle/Payload/OneDrive.app/AlmostThere.storyboardc/AlmostThere.nib  
  inflating: /var/root/needle/Payload/OneDrive.app/AlmostThere.storyboardc/Info.plist  
  inflating: /var/root/needle/Payload/OneDrive.app/AlmostThere.storyboardc/TFW-VF-rtU-view-PId-EF-Lf2.nib  
  inflating: /var/root/needle/Payload/OneDrive.app/AnalyticsSummaryFRECollectionViewCell.nib  
  inflating: /var/root/needle/Payload/OneDrive.app/AnalyticsSummaryFooterCollectionReusableView.nib  
...
```

**Comment by marco-lancini** [comment] 2017-01-19 11:49
mmmh I have a feeling this might have the same root cause as issue https://github.com/mwrlabs/needle/issues/67

**Comment by marco-lancini** [comment] 2017-01-20 17:26
Thanks to @TheBananaStand, this should be fixed in `develop`.
I'm gonna close it for now, let me know if you experience the same issue

**Closed by marco-lancini** 2017-01-20 17:26 UTC
Labels: bug report, waiting_feedback
