### ISSUE TITLE
sh: lipo: command not found   on kali

### ISSUE THREAD

**Issue by nanshihui** [mwrlabs/needle#198] opened 2017-09-27 07:20 UTC
as you said that needle worked both on mac and kali.
however i tried it ,it failed.

**Comment by lianfeng30** [comment] 2017-09-27 09:04
兄弟 看这：https://github.com/mwrlabs/needle/wiki/Installation-Guide 嘻嘻

**Comment by marco-lancini** [comment] 2017-09-27 18:48
duplicate of #172

**Closed by marco-lancini** 2017-09-27 18:48 UTC
Labels: duplicate
