### ISSUE TITLE
constants.py: Clutch2 no longer hosted on http://cydia.iphonecake.com/

### ISSUE THREAD

**Issue by n0ttab0t** [mwrlabs/needle#144] opened 2017-03-23 17:44 UTC
## Issue
Repo http://cydia.iphonecake.com/ now uses Rasticrac and has pulled Clutch2 from their repository. Thus, SETUP_DEVICE fails to install Clutch2.

## Solution
Change search path and package name in constants.py to a repo of your choosing.

**Comment by marco-lancini** [comment] 2017-03-27 08:12
Duplicate of #117

**Closed by marco-lancini** 2017-03-27 08:12 UTC
