### ISSUE TITLE
Error when the application has a whitespace in the name

### ISSUE THREAD

**Issue by platix** [mwrlabs/needle#191] opened 2017-08-28 21:06 UTC
## Issue
When the app name has a whitespace, needle doesn't scape well the location and the scripts fails.

[*] Retrieving app's metadata...
[*] Pulling: '/private/var/containers/Bundle/Application/703F3017-0AF7-4B69-B643-B272646E7CC6/e Name.app'"'"'/Info.plist' -> /root/.needle/tmp/plist
[!] IOError: [Errno 2] No such file or directory: '/root/.needle/tmp/plist'

**Comment by marco-lancini** [comment] 2017-08-28 21:16
duplicate of #80

**Closed by marco-lancini** 2017-08-28 21:16 UTC
