### ISSUE TITLE
Issue with blanks in the app name.

### ISSUE THREAD

**Issue by florian-eichelberger** [mwrlabs/needle#183] opened 2017-07-04 11:21 UTC
### Expected behaviour
The app should be able to download files correctly e.g. Info.plist

### Actual behaviour
The app seems to have some issues with blanks in the name of the app.

### Steps to reproduce
1. start needle agent on device and needle.py on the host
2. use binary/info/metadata -> run
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

## Environment

iOS 9.3.1

#### Needle Version

- Framework (on your machine): 1.3.1 
- Agent (on your device): 1.0.5

#### Workstation Operating System

Kali Linux

#### Device iOS Version

iOS 9.3.1

By running the module on an app with a blank in the name, the following thing happens

[*] Pulling: /private/var/containers/Bundle/Application/F54A6AF0-9DFE-4C93-B0EC-6475D3E5ACB7/App%20Name.app/Info.plist -> /home/user/.needle/tmp/plist
[!] IOError: [Errno 2] No such file or directory: '/home/user/.needle/tmp/plis

The path is constructed incorrectly as by using the following path, the file can be found.

root# ls -al /private/var/containers/Bundle/Application/F54A6AF0-9DFE-4C93-B0EC-6475D3E5ACB7/App\ Name.app/Info.plist 
-rw-r--r-- 1 _installd _installd 6400 Jun  2 16:02 /private/var/containers/Bundle/Application/F54A6AF0-9DFE-4C93-B0EC-6475D3E5ACB7/App Name.app/Info.plist

**Comment by marco-lancini** [comment] 2017-07-04 12:30
duplicate of #151

**Closed by marco-lancini** 2017-07-04 12:30 UTC
Labels: duplicate
